server:
  url: http://localhost:${server.port}
  port: 51033
  
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      database: mp_captures
      host: localhost    
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health      
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

authorization:
  service: MP-AUTHORIZATIONS
  
breakdowns:
  service: MP-BREAKDOWNS
  
psp:
  service: MP-PSPSERVICE
  
beneficiary:
  service: MP-BENEFICIARIES  
  
transaction:
  service: MP-TRANSACTIONS  

oauth:
  client_id: mp_captures_client
  client_secret: NmQgNjAgNTMgNjMgZDIgMDkgMTcgMzUgOWYgZmQgYTMgM2IgYTkgNzYgYzYg

auth:
  service: MP-AUTHSERVER
  path: /oauth/token  
  
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:50068/validateClient  

management:
  endpoints:
    web:
      exposure:
        include: "*"    
amqp:
  captures:
    queue:
      transaction:
        status:
          updated:
            request: create_capture_response_queue
    exchange:
      completed:
        capture: completed_capture            
            
  events:
    queue:
      created:
        request: createad_event_queue
    exchange:
      created: created_events
    key:
      created:
        request: events   
        
---
spring:
  profiles: integration
  data:
    mongodb:
      database: mp_captures
      host: localhost
      port: 27018     
  rabbitmq:
    host: o2c.ovh
    port: 5672
    username: master-pay
    password: master123      

server:
  url: http://o2c.ovh:${server.port}
