server:
  port: 8880
  
spring:
  cloud:
    gateway:
      discovery: 
        locator: 
          enabled: true
      globalcors:
        corsConfigurations:
           '[/**]':
              allowedOrigins: "*"
              allowedMethods:
                - GET     
                - POST
                - PUT
                - DELETE
                - OPTIONS           
      routes:
      - id: MP-PageRequests
        uri: lb://MP-PageRequests
        predicates:
        - Path=/paymentPages
        filters:
        - RewritePath=/paymentPages, /paymentPages
      - id: MP-PageRequests-token
        uri: lb://MP-PageRequests
        predicates:
        - Path=/token
        filters:
        - RewritePath=/token, /token
      - id: MP-Transactions
        uri: lb://MP-Transactions
        predicates:
        - Path=/transactions
        - Method=GET
        filters:
        - RewritePath=/transactions, /
      - id: MP-Transactions-withId
        uri: lb://MP-Transactions
        predicates:
        - Path=/transactions/{id}
        - Method=GET
        filters:
        - RewritePath=/transactions/(?<id>.*), /$\{id}
      - id: MP-AuthServer
        uri: lb://MP-AuthServer        
        predicates:
        - Path=/oauth/token
        filters:
        - RewritePath=/oauth/token, /oauth/token
      - id: MP-AuthServer-validate
        uri: lb://MP-AuthServer        
        predicates:
        - Path=/validateClient
        filters:
        - RewritePath=/validateClient, /validateClient
      - id: MP-Authorizations
        uri: lb://MP-Authorizations
        predicates:
        - Path=/transactions/{transactionId}/authorizations
        - Method=GET
        filters:
        - RewritePath=/transactions/(?<transactionId>.*)/authorizations, /transactions/$\{transactionId}/authorizations
      - id: MP-Captures
        uri: lb://MP-Captures
        predicates:
        - Path=/transactions/{transactionId}/captures
        filters:
        - RewritePath=/transactions/(?<transactionId>.*)/captures, /transactions/$\{transactionId}/captures
      - id: MP-Captures-withId
        uri: lb://MP-Captures
        predicates:
        - Path=/transactions/{transactionId}/captures/{paymentId}
        filters:
        - RewritePath=/transactions/(?<transactionId>.*)/captures/(?<paymentId>.*), /transactions/$\{transactionId}/captures/$\{paymentId}
      - id: MP-Refunds
        uri: lb://MP-Refunds
        predicates:
        - Path=/transactions/{transactionId}/refunds
        filters:
        - RewritePath=/transactions/(?<transactionId>.*)/refunds, /transactions/$\{transactionId}/refunds
      - id: MP-Refunds-withId
        uri: lb://MP-Refunds
        predicates:
        - Path=/transactions/{transactionId}/refunds/{paymentId}
        filters:
        - RewritePath=/transactions/(?<transactionId>.*)/refunds/(?<paymentId>.*), /transactions/$\{transactionId}/refunds/$\{paymentId}       
      - id: MP-Breakdowns
        uri: lb://MP-Breakdowns
        predicates:
        - Path=/breakdowns
        filters:
        - RewritePath=/breakdowns, /
        - RewritePath=/breakdowns/(?<id>.*), /$\{id}        
      - id: MP-Breakdowns-withId
        uri: lb://MP-Breakdowns
        predicates:
        - Path=/breakdowns/{id}
        filters:
        - RewritePath=/breakdowns/(?<id>.*), /$\{id}
      - id: MP-Balances
        uri: lb://MP-Balances
        predicates:
        - Path=/balances
        filters:
        - RewritePath=/balances, /
      - id: MP-Balances-withId
        uri: lb://MP-Balances
        predicates:
        - Path=/balances/{id}
        filters:
        - RewritePath=/balances/(?<id>.*), /$\{id}
      - id: MP-Payouts
        uri: lb://MP-Payouts
        predicates:
        - Path=/payouts       
        filters:
        - RewritePath=/payouts, /
      - id: MP-Payouts-withId
        uri: lb://MP-Payouts
        predicates:
        - Path=/payouts/{id}
        filters:
        - RewritePath=/payouts/(?<id>.*), /$\{id}
      - id: MP-PageRequests-complete
        uri: lb://MP-PageRequests
        predicates:
        - Path=/completeTransaction
        filters:
        - RewritePath=/completeTransaction, /completeTransaction
      - id: MP-MarketPlaces
        uri: lb://MP-MarketPlaces
        predicates:
        - Path=/marketplace
        filters:
        - RewritePath=/marketplace, /
      - id: MP-Exports
        uri: lb://MP-Exports
        predicates:
        - Path=/exports
        filters:
        - RewritePath=/exports, /exports
      - id: MP-Users-beneficiaries
        uri: lb://MP-Users
        predicates:
        - Path=/beneficiaries/{beneficiaryId}/users
        filters:
        - RewritePath=/beneficiaries/(?<beneficiaryId>.*)/users, /beneficiaries/$\{beneficiaryId}/users
      - id: MP-Users-beneficiaries-withId
        uri: lb://MP-Users
        predicates:
        - Path=/beneficiaries/{beneficiaryId}/users/{userId}
        filters:
        - RewritePath=/beneficiaries/(?<beneficiaryId>.*)/users/(?<userId>.*), /beneficiaries/$\{beneficiaryId}/users/$\{userId}
      - id: MP-Users-marketplaces
        uri: lb://MP-Users
        predicates:
        - Path=/marketplaces/{marketplaceId}/users
        filters:
        - RewritePath=/marketplaces/(?<marketplaceId>.*)/users, /marketplaces/$\{marketplaceId}/users
      - id: MP-Users-marketplaces-withId
        uri: lb://MP-Users
        predicates:
        - Path=/marketplaces/{marketplaceId}/users/{userId}
        filters:
        - RewritePath=/marketplaces/(?<marketplaceId>.*)/users/(?<userId>.*), /marketplaces/$\{marketplaceId}/users/$\{userId}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false      
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health      
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        
    
management:
  endpoints:
    web:
      exposure:
        include: "*"

---
spring:
  profile: docker
  server:
    port: ${port:8880}
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER:eureka-server}:${EUREKA_PORT:8761}/eureka/  
  
