server:
  port: 50061
  
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
      
management:
  endpoints:
    web:
      exposure:
        include: "*"    
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health      
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}


amqp:
  money-provider:
    exchange:
      sent:
        money: sent_money
  events:
    queue:
      created:
        request: createad_event_queue
    exchange:
      created: created_events
    key:
      created:
        request: events

smoney:
  baseUrl: https://rest-pp.s-money.fr/api/sandbox/payments
  accessToken: NTs1MjI7TnJTTFBIRVVxQQ==
  
---
spring:
  profiles: integration
  rabbitmq:
    host: o2c.ovh
    port: 5672
    username: master-pay
password: master123  
