server:
  port: 50082
  
spring:
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: fb876a89e18100
    password: 0b16397ff51d54
    starttls:
      enable: true

    
  multirabbitmq:
    rabbitmq:
      defaultConnection: true
      host: localhost
      port: 6672
      username: guest
      password: guest
        
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health      
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:50068/validateClient    

param:
  service: MP-PARAMS
   
amqp:
  marketplace:
    notifications:
      queue:
        marketplace_message_notifications_queue
      exchange:
        publish:
           marketplace_published_messages
        
  events:
    queue:
      created:
        request: createad_event_queue
    exchange:
      created: created_events
    key:
      created:
        request: events                  
