server:
  port: 51082
  
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: o2pmasterpay@gmail.com
    password: "!MasterPay123!"
    properties:
      mail:
        smtp:
          starttls:
            enable: true  
    
  multirabbitmq:
    rabbitmq:
      defaultConnection: true
      host: localhost
      port: 6672
      username: master-pay
      password: ZDEgYjggMjcgYTcgYWIg

email:
  from: export@o2c.ovh
  body: "Please find attached the report. \n\nRegards, \nMasterPay Team"


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health      
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8880/validateClient    

param:
  service: MP-PARAMS
   
amqp:
  marketplace:
    notifications:
      queue: marketplace_message_notifications_queue
      exchange:
        publish: marketplace_published_messages
        
  events:
    queue:
      created:
        request: createad_event_queue
    exchange:
      created: created_events
    key:
      created:
        request: events                  
