server:
  port: 51060
  
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
  data:
    mongodb:
      database: mp_page_request
      host: localhost
      
management:
  endpoints:
    web:
      exposure:
        include: "*"    
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health      
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8880/validateClient  
      
amqp:
  init-transactions:
    exchange:
      created:
        init-transaction: created_init_transaction
  complete-transactions:
    exchange:
      completed: 
        transaction: completed_transaction
  events:
    queue:
      created:
        request: createad_event_queue
    exchange:
      created: created_events
    key:
      created:
        request: events
        
oauth:
  client_id: mp_init_transaction_client
  client_secret: NzQgYTkgMjkgNTEgZTQgNmYgN2QgZDAgZDUgMTEgZjggOWYgZDggNWMgZGIg

captures:
  service: MP-CAPTURES

auth:
  service: MP-AUTHSERVER
  path: /oauth/token        
  
beneficiary:
  service: MP-BENEFICIARIES
  
breakdowns:
  service: MP-BREAKDOWNS
  
param:
  service: MP-PARAMS
  
webapp:
  url: http://localhost:4200
  
dalenys:
  identifier: O2C-TEST
  accountKey: x7#4D8LCP}ddjh6/
  version: 3.0
  
---
spring:
  profiles: integration
  data:
    mongodb:
      database: mp_page_request
      host: localhost
      port: 27018
  rabbitmq:
    host: rabbitmq.o2c.ovh
    port: 5672
    username: master-pay
    password: master123      
      
webapp:
  url: https://webapp-integration.o2c.ovh
  
---
spring:
  profiles: qa
  data:
    mongodb:
      database: mp_page_request
      host: localhost
      port: 27018
  rabbitmq:
    host: localhost
    port: 5672
    username: master-pay
    password: master123      
      
webapp:
  url: https://webapp-qa.o2c.ovh
  
dalenys:
  identifier: O2C-TEST2
  accountKey: Bg7:[6./m,<Oa#ss
  version: 3.0  
---
spring:
  profiles: docker
  data:
    mongodb:
      database: mp_page_request
      host: ${MONGO_SERVER:o2c-mongodb}
      port: ${MONGO_PORT:27018}
  rabbitmq:
    host: ${RABBIT_SERVER:rabbitmq}
    port: ${RABBIT_PORT:5672}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}

server: 
  port: ${PORT:51060}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER:eureka-server}:${EUREKA_PORT:8761}/eureka/
  instance:   
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true

security:
  oauth2:
    resource:
      userInfoUri: http://${API_GATEWAY_SERVER:api-gateway-server}:${API_GATEWAY_PORT:8880}/validateClient  

webapp:
  url: ${WEBAPP_URL}
 
dalenys:
  identifier: ${DALENYS_IDENTIFIER}
  accountKey: ${DALENYS_ACCOUNTKEY}
  version: ${DALENYS_VERSION:3.0}  
